apiVersion: v1
kind: Service
metadata:
  name: cleanarqapi-service
  labels:
    name: cleanarqapi-service
    app: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
  selector:
    app: cleanarqapi
    type: microservice