apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanarqapi-deploy
  labels:
    name: cleanarqapi-deploy
    app: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cleanarqapi
      type: microservice
  template:
    metadata:
      name: cleanarqapi-pod
      labels:
        app: cleanarqapi
        type: microservice
    spec:
      containers:
        - name: cleanarqapi-app
          image: nicolasundiano/cleanarqapi:v2.#{Build.BuildId}#
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__AppConnection
              value: Server=sqlserver-app-service;Database=cleanArq;User=sa;Password=Nosejose20!
            - name: ConnectionStrings__IdentityAuthConnection
              value: Server=sqlserver-security-service;Database=cleanArq.identity;User=sa;Password=Nosejose20!