apiVersion: v1
kind: Pod
metadata:
  name: sqlserver-security-pod
  labels:
    app: cleanarqapi
    name: sqlserver-security-pod
spec:
  containers:
    - name: sqlserver-security
      image: mcr.microsoft.com/mssql/server
      ports:
        - containerPort: 1433
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "Nosejose20!"