apiVersion: v1
kind: Service
metadata:
  name: sqlserver-security-service
  labels:
    name: sqlserver-security-service
    app: database
spec:
  type: LoadBalancer
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: cleanarqapi
    name:  sqlserver-security-pod